services:
  mysql_security:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: security_db
      MYSQL_ROOT_PASSWORD: "root"
      
    ports:
      - "3308:3306"
    volumes:
      - mysql_security_data:/var/lib/mysql

  mysql_marketing:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: marketing_db
      
    ports:
      - "3309:3306"
    volumes:
      - mysql_marketing_data:/var/lib/mysql

  mysql_product:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: product_db
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3310:3306"
    volumes:
      - mysql_product_data:/var/lib/mysql

volumes:
  mysql_security_data:
  mysql_marketing_data:
  mysql_product_data:
  
