services:
  mysql_security:
    image: mysql:latest
    container_name: security
    environment:
      MYSQL_DATABASE: security_db
      MYSQL_ROOT_PASSWORD: "root"
      
    ports:
      - "3308:3306"
    volumes:
      - mysql_security_data:/var/lib/mysql

  mysql_marketing:
    image: mysql:latest
    container_name: marketing
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: marketing_db
      
    ports:
      - "3309:3306"
    volumes:
      - mysql_marketing_data:/var/lib/mysql

  mysql_product:
    image: mysql:latest
    container_name: product
    environment:
      MYSQL_DATABASE: product_db
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3310:3306"
    volumes:
      - mysql_product_data:/var/lib/mysql
  rabbitmq:
        image: "rabbitmq:3.8.6-management"
        container_name: rabbitmq-rent-car
        ports:
          - 5672:5672
          - 15672:15672
volumes:
  mysql_security_data:
  mysql_marketing_data:
  mysql_product_data:
  
